### ISSUE TITLE
doesn't work with facebook/react

### ISSUE THREAD

**Issue by juliangruber** [nodesource/ncm-cli#115]
```bash
$ goto facebook react
$ ncm report

╔══════════════╗
║ react Report ║
╚══════════════╝

‼︎ Unable to fetch project report. Have you run `ncm signin`?

```

I am signed in, so there must be something else going on. This was before I ran `yarn`, so while there's no `node_modules/` there's a `package.json` and a `yarn.lock`, which should be all this tool needs.

**Comment by juliangruber** [comment]
Same error after installing the dependencies.

**Comment by juliangruber** [comment]
Is there a way to get more error output? I think @Raynos was wanting this too.

**Comment by Raynos** [comment]
i added a functionality and it surfaced a message for this previously which was `cannot find node_modules` or something; there's a `NCM_DEV=1` flag i think that should add that back ? 

But yeah error reporting is a little opague.

**Comment by juliangruber** [comment]
No change with `NCM_DEV=1`. And the underlying module [universal-module-tree](https://github.com/nodesource/universal-module-tree) works without `node_modules` too, as long as there's a lock file.

**Comment by pmuellr** [comment]
I think it's this line: 

https://github.com/facebook/react/blob/9d77a317bf5bde7e6edd3c8cd0ebb00feb447223/package.json#L54

```
    "eslint-plugin-react-internal": "link:./scripts/eslint-rules/",
```

I noticed `npm install` complained about this, so I just removed it and ran `ncm-cli` again and it worked fine.

**Comment by juliangruber** [comment]
right! so in that case universal-module-tree could only look at `node_modules/`. I'll work on this.
