### ISSUE TITLE
`ncm help` says the command is `ncm`

### ISSUE THREAD

**Issue by pmuellr** [nodesource/ncm-cli#117]
```console
$ ncm-cli
...
Usage:
┌─────────────────────────┐
│ ncm <command> [options] │
└─────────────────────────┘
...
ncm config list
ncm config reset
ncm config del <key>
...
```

It should print `ncm-cli` instead of `ncm` ...

**Comment by Fishrock123** [comment]
Technically we install `bin`s for both: https://github.com/nodesource/ncm-cli/blob/master/package.json#L32-L35

**Comment by Fishrock123** [comment]
I suppose the docs should probably mention this.

**Comment by juliangruber** [comment]
I hope no one will try to run `ncm-cli` and `ncm` establishes itself as the cli name

**Comment by Fishrock123** [comment]
I think this is probably fine to close
