### ISSUE TITLE
`ncm report` (without --long) should print details

### ISSUE THREAD

**Issue by pmuellr** [nodesource/ncm-cli#118]
It seems appropriate for `ncm report --long` to just print one line per package, but I think for the non- `--long` version, might as well go ahead and print the details.

Otherwise, I'm left cut/paste the package names into new `ncm detail` commands.

**Comment by Raynos** [comment]
i've also had a desire for `ncm report --detail --filter=security,high` 

For compliance failures the licence failure is shown in the module list.

For security failures; seeing the individual security failures is useful

For risk failures; I'm not sure how actionable or useful that information is in the `ncm-cli report` output as it's more about quality of the dependency and less so about "this dependency has a security vulnerability that needs to be resolved no matter what"
