### ISSUE TITLE
badge with link to report

### ISSUE THREAD

**Issue by pmuellr** [nodesource/ncm-cli#119]
It would be fun to see if you could create a "badge" story for use in a package's `README.md` file, that would return a link to a run of the package's `package.json` with a full report.  Not quite sure how this work, presumably it would mean the badge would contain a link that included the public gh repo / path to package.json (able to handle mono-repos).  Which would mean anyone could get that report, without an account.  ¯\_(ツ)_/¯

**Comment by Gioyik** [comment]
We can generate this with the GitHub Actions integration now.
