### ISSUE TITLE
box design conflicts with narrow window

### ISSUE THREAD

**Issue by juliangruber** [nodesource/ncm-cli#144]
<img width="640" alt="Screenshot 2019-04-26 at 14 06 33" src="https://user-images.githubusercontent.com/10247/56806552-8a522600-682c-11e9-86c8-2c2c865bd8cc.png">

This box is unnecessarily wide.

I suggest to either remove the boxes (preferred), or make them only as wide as necessary.

**Comment by Fishrock123** [comment]
It's a bug. We should calculate by the cli width....
