### ISSUE TITLE
[Permanent Fix] Error fetching a report for a project using git dependencies 

### ISSUE THREAD

**Issue by Jazneil** [nodesource/ncm-cli#152]
The temporary fix for this issue was implemented in #151

**Comment by brycebaril** [comment]
Please include a test in the permanent fix as well.

**Comment by Jazneil** [comment]
@edsadr, since this issue would be a permanent fix and a temporary workaround fix, is in #151 what should be the severity of this issue? @mnedelko can you please chime in for priority.

**Comment by Fishrock123** [comment]
This issue as described does not appear to exist in any testing that we have ever done.
