### ISSUE TITLE
install doesn't handle child install process errors

### ISSUE THREAD

**Issue by mnedelko** [nodesource/ncm-cli#159]
When using `ncm install` I am receiving the following error.

![image](https://user-images.githubusercontent.com/6106392/59472021-dadc0d80-8df1-11e9-9235-eb27c70637f4.png)

- I am logged in
- npm install hapi works though:
![image](https://user-images.githubusercontent.com/6106392/59472039-f21afb00-8df1-11e9-9f85-24a895d523e1.png)

**Comment by Fishrock123** [comment]
https://github.com/nodesource/ncm-cli/pull/163 should at least tell the user what went wrong in the subcommand / `npm`.

Likely there is no fix on our end.

**Comment by Raynos** [comment]
Why would mike not be able to spawn `npm` as a child process :(

**Comment by Raynos** [comment]
https://stackoverflow.com/questions/43230346/error-spawn-npm-enoent

Apparently the binary is called `npm.cmd` or something on windows.

**Comment by juliangruber** [comment]
This is a popular solution: https://www.npmjs.com/package/cross-spawn

**Comment by mnedelko** [comment]
'cross-spawn' requires me to npm install a module that I require into my code. This doesn't seem the right solution to fix an installation issue since those are different workflows?

**Comment by mnedelko** [comment]
'cross-spawn' is a module you need to npm install and require in your code. That doesn't seem to align with the workflow described above which is specific to installing a module.

**Comment by juliangruber** [comment]
cross-spawn is a module ncm-cli can use internally to spawn npm for this command ;)
