### ISSUE TITLE
ncm whitelist --add doesn't work

### ISSUE THREAD

**Issue by mnedelko** [nodesource/ncm-cli#161]
'ncm whitelist --add' throws the following error:

![image](https://user-images.githubusercontent.com/6106392/59472163-6e154300-8df2-11e9-9b1d-48a2b452fabd.png)

I am:
- logged into NodeSource account
- upgraded to latest ncm

**Comment by Fishrock123** [comment]
Yeah this is technically just a duplicate of https://github.com/nodesource/ncm-cli/issues/160
