### ISSUE TITLE
Improve semver ranges on `ncm install`

### ISSUE THREAD

**Issue by julianduque** [nodesource/ncm-cli#172]
When giving a short semver version (major.minor) without a patch it doesn't recognize the version:

```
⬢  fetcher [master] (v10.16.0) ncm install qs@0.2

X Unrecognized module syntax: qs@0.2

|➔ Install this module? (y/N)
```

**Comment by Fishrock123** [comment]
Unsure if this is `bug` or `enhancement`, but is essentially very related to https://github.com/nodesource/ncm-cli/issues/133.

**Comment by juliangruber** [comment]
The bug might be to abort when a version can't be parsed, and the enhancement might be to support all of the syntax npm also supports
