### ISSUE TITLE
ncm details command fails when executed at a directory with a package.json and lacking node_modules 

### ISSUE THREAD

**Issue by edsadr** [nodesource/ncm-cli#178]
When executing `npm details module` at a directory with a package.json and lacking node_modules the command fails, if you execute it in a directory without a package.json it works without any issue, same when you execute it  a directory containing a package.json and full modules installed at node_modules

**Comment by juliangruber** [comment]
The error seems to happen because `universal-module-tree` gets executed during this command

**Comment by Fishrock123** [comment]
Yeah this is pretty bad IMO. Errors thrown by `universal-module-tree` in `details` should probably just get ignored

**Comment by Fishrock123** [comment]
Hah, turns out we already do that but for some odd reason `universal-module-tree` returns `ERR_ASSERTION` here instead of `ENOENT`... which I think is essentially a bug.
