### ISSUE TITLE
[NSolidL] NSolid for Lambda Refinements

### ISSUE THREAD

**Issue by mnedelko** [nodesource/ncm-cli#184]
This work intends to cover both tests and a fix for wrong average invocation duration (see below).

AS 
A user

I WANT TO
See a correct aggregate of my average invocation duration displayed per functions

SO THAT I CAN
effectively identify whether it adheres/ contravenes to expected values across my function invocations.

**Comment by juliangruber** [comment]
I think the correct place for this issue is nodesource/serverless-schema

**Comment by juliangruber** [comment]
I'm cautiously estimating this as a `5` as it potentially involves the complex SQL around lambdas and aggregation.
