### ISSUE TITLE
"Unable to find project at ..." error

### ISSUE THREAD

**Issue by Fishrock123** [nodesource/ncm-cli#72]
> `X Unable to find project at: /Users/Jeremiah/Documents/here-be-dragons`

This directory has `node_modules` but no `package.json`. I think that `universal-module-tree` should be able to be forced to run regardless.

**Comment by Jazneil** [comment]
Hey @Fishrock123 can you please add priority and an estimate to this bug?

**Comment by juliangruber** [comment]
`universal-module-tree` can't run properly in that case because it won't be able to distinguish toplevel from sublevel dependencies, and therefore can't build a dependency tree.

We might support this in a new `flat` mode however, if you think that's useful?

**Comment by Fishrock123** [comment]
@juliangruber While that would be ideal, for now the error message is wrong.

We don't intercept the error from `u-m-t` correctly, which should say that an install has not been done.
