### ISSUE TITLE
cryptic error for `ncm-cli report`

### ISSUE THREAD

**Issue by Raynos** [nodesource/ncm-cli#84]
```
raynos at raynos-Dell-Precision-M3800  
~/nodesource/ncm-cli on filter-level*
$ ncm-cli report

╔════════════════╗
║ ncm-cli Report ║
╚════════════════╝

‼︎ Unable to fetch project report. Cannot read property 'packageVersions' of undefined

```

Uncaught exception with `res.packageVersions` because we are not handling graphql response properly; missing error handling somewhere.

**Comment by Fishrock123** [comment]
I think that https://github.com/nodesource/ncm-cli/commit/0ff784d42d24c6b0e13c70d908555c450d16c495 & https://github.com/nodesource/ncm-cli/commit/da56bc1977d48e60f4b9d909617c9f79e8ac4dbe combined effectively solve this.
